#!/usr/bin/env python3
"""Emit a Workflow that BUILDS interactive visualizer tools (Sonnet build -> Opus verify).

Each job writes a self-contained tools/<slug>.html widget and inserts a {{tool:<slug>}} marker
into its mapped chapter (all distinct chapters -> no concurrent .md edits). build.py's
expand_tools() inlines it and write_tools_hub() adds it to /tools automatically.

Usage: python3 scripts/gen_tools_workflow.py [--ids slug1 slug2 ...]
"""
import argparse, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# slug, title, chapter (for the {{tool:}} marker + "used in"), rebuild (overwrite, no new marker), brief.
SPECS = [
 {"slug":"tokenizer-playground","title":"Tokenizer playground: train a real byte-level BPE","chapter":"02-transformer/01-tokenization","rebuild":True,
  "brief":"REBUILD the existing tool into a REAL byte-level BPE, not a simplified whitespace splitter. In-browser: a textarea seeded with a sample corpus + a 'vocab size / num-merges' slider + a 'Train' button. On train: run actual byte-level BPE — start from the 256 byte tokens, iteratively find the most frequent adjacent pair and merge, recording the ordered merge list; show a live-updating merges table (rank, pair -> new token) and the growing vocab. Then an encode box: type text, byte-encode, apply the learned merges greedily by rank, and render the resulting tokens as colored chips with the token count and the compression ratio (bytes/token). A decode readout reconstructs the exact bytes (prove round-trip). Include a small step-through 'animate merges' that highlights each merge as it is applied to a sample word. Correctness is the point: real GPT-style byte-level BPE (bytes 0-255 base, merge by frequency, deterministic tie-break, greedy rank-ordered encode, exact decode). Keep it fast (cap corpus/merges so training is instant)."},
 {"slug":"self-attention-explorer","title":"Self-attention explorer: Q, K, V and the attention matrix","chapter":"02-transformer/03-attention-from-scratch",
  "brief":"Let the reader FEEL scaled dot-product attention. Controls: a short editable token sequence (default e.g. 'the cat sat on the mat', tokenized by word, up to ~10 tokens); a 'causal mask' toggle; a temperature/1-over-sqrt(dk) scale toggle; a head selector (2-3 preset heads with different fixed random Q/K projections so the pattern changes). Render the S x S attention-weight heatmap (rows=query, cols=key), each cell shaded by softmax weight with the numeric value on hover; grey out masked cells when causal. Below, for a selected query token, show its softmax distribution as a bar row and the resulting weighted-sum 'context' as a small bar vector. Use small fixed pseudo-random d=8 embeddings + fixed random W_q/W_k/W_v seeded deterministically so it is reproducible; compute real QK^T/sqrt(dk), mask, softmax, and V-weighted sum. This is the single most important transformer intuition — make the heatmap the star."},
 {"slug":"softmax-temperature","title":"Softmax & temperature: from logits to a distribution","chapter":"01-foundations/02-probability-information",
  "brief":"Show how a logit vector becomes a probability distribution and how temperature reshapes it. Controls: ~6 editable logit values (number inputs or draggable bars) and a temperature slider (0.1-3.0, log-ish). Render the input logits as bars and the softmax(logits/T) probabilities as a second set of bars that update live; display the Shannon entropy H = -sum p log p (in nats and bits) and the argmax/perplexity. Show the T->0 (one-hot) and T->inf (uniform) limits as annotations. Compute real softmax with the max-subtraction trick. Tie the readout to LLM sampling (low T = sharp/greedy, high T = diverse)."},
 {"slug":"gradient-descent-playground","title":"Gradient descent playground: optimizers on a loss surface","chapter":"01-foundations/03-calculus-optimization",
  "brief":"A 2D loss-surface sandbox. Draw contour lines of a convex quadratic bowl whose condition number kappa is set by a slider (an ill-conditioned valley when kappa is high). Controls: optimizer (SGD, SGD+momentum, Adam), learning-rate slider, momentum/beta slider, a 'start point' the user can drag, and Step / Run / Reset. Animate the optimizer trajectory as a path of dots on the contour plot, computing the REAL update rules each step from the analytic gradient of the quadratic. Show the loss-vs-step curve alongside. Demonstrate the key intuitions: too-high LR diverges (path explodes), momentum overshoots then settles, Adam is scale-invariant across the ill-conditioned axes, and high kappa slows plain SGD. Keep the math exact (gradient of 0.5*(a*x^2 + b*y^2))."},
 {"slug":"backprop-graph","title":"Backprop on a computation graph","chapter":"01-foundations/07-autodiff-pytorch",
  "brief":"An interactive computation graph for a tiny expression (e.g. L = (w*x + b - y)^2, or a 2-node MLP neuron with a sigmoid). Draw the DAG of nodes (inputs, ops, output). Let the user set the leaf values (w, x, b, y) with number inputs. Forward pass: show each node's value. Backward pass (a 'backprop' button that animates from the loss back to the leaves): show the local derivative on each edge and the accumulated gradient dL/dnode on each node, so the chain rule is visible edge by edge. End with dL/dw etc. matching a from-scratch analytic check. This makes autodiff concrete: values flow forward, gradients flow backward, chain rule = multiply along the path."},
 {"slug":"normalization-explorer","title":"LayerNorm vs RMSNorm, live","chapter":"02-transformer/06-transformer-block",
  "brief":"Show what normalization does to an activation vector. The user edits/drags a small vector (~8 dims) of activations shown as bars (some large, some negative). Toggle between LayerNorm (subtract mean, divide by std, then gain*x+bias) and RMSNorm (divide by RMS, then gain*x — no mean subtraction, no bias) with gain/bias sliders. Render the output bars live and print mean, variance/RMS before and after. Demonstrate: LayerNorm centers AND scales (output mean 0, var 1 before affine); RMSNorm only scales (cheaper, keeps direction, no re-centering). Compute the real statistics. Note the pre-norm residual context."},
 {"slug":"embedding-similarity","title":"Embeddings & cosine similarity in 2D","chapter":"02-transformer/02-embeddings-input",
  "brief":"A 2D plane with ~8 draggable word-vector points (labeled tokens). As the user drags, live-update a similarity readout: pick two tokens (or hover) and show their dot product, cosine similarity, and Euclidean distance. Draw the angle between two selected vectors. Optionally a 'king - man + woman ~ queen' analogy demo: draw the vector arithmetic as arrows and highlight the nearest point to the result. Compute real dot/cosine/norm. Teaches: embeddings are directions in space; cosine similarity = angle; analogies = vector arithmetic; magnitude vs direction."},
 {"slug":"kv-cache-growth","title":"KV cache growth during decoding","chapter":"07-inference-serving/01-anatomy-inference",
  "brief":"Animate the KV cache filling up token by token during autoregressive decode, and show why it dominates long-context memory. Controls: n_layers, n_kv_heads (with an MHA-vs-GQA toggle showing the KV-head reduction), head_dim, dtype (fp16/bf16=2B, fp8=1B), and a 'generate' button that advances the sequence length. Render a grid/bar that grows as tokens are added (2 * L * n_kv_heads * head_dim * seq_len * bytes) with a live GB readout and a comparison to model-weights size. Show GQA shrinking the bar by the head-group ratio. Contrast prefill (parallel, one big fill) vs decode (one column per step). Use the exact KV-cache formula; this complements the kv-cache-budgeter calculator with a visual/animated view."},
 {"slug":"moe-router","title":"Mixture-of-Experts routing & load balance","chapter":"02-transformer/09-mixture-of-experts",
  "brief":"Visualize top-k MoE routing. Show N tokens (dots) and E experts (columns). A router assigns each token a softmax over experts (from fixed seeded pseudo-random gate logits per token, re-rollable); route each token to its top-k experts (k slider, 1-2) and draw lines token->expert. Show per-expert load bars, the capacity factor / dropped-tokens when an expert overflows a capacity limit (slider), and the load-balancing (auxiliary) loss / coefficient-of-variation of the loads. A 'shuffle' button re-rolls the gates. Teaches: sparse activation (only k of E experts run per token), the load-imbalance problem, capacity + drop, and why an aux load-balancing loss is needed. Compute real softmax gating, top-k, loads, and the CV."},
 {"slug":"quantization-explorer","title":"Quantization explorer: fp32 -> int8 / int4 / NF4","chapter":"04-kernels-efficiency/07-quantization-ptq",
  "brief":"Show post-training quantization on a weight tensor. Generate a bell-shaped weight distribution (Gaussian, with an outlier slider). Choose a format: int8 (per-tensor absmax affine/symmetric), int4 (16 levels), and NF4 (the non-uniform normal-float levels). Draw the original values as a histogram with the quantization grid overlaid (the representable levels), and a second histogram of the quantization ERROR (dequantized - original). Show bytes/param (4->1->0.5), the RMSE, and the max abs error. Demonstrate: fewer bits = coarser grid = more error; outliers stretch per-tensor absmax scale and hurt everyone (motivating per-channel/group scaling and NF4's normal-optimal levels). Real quantize/dequantize math (scale = absmax/qmax, round, clamp, dequant)."},
 {"slug":"lr-schedule-explorer","title":"Learning-rate schedules: warmup, cosine, WSD","chapter":"03-pretraining/10-lr-schedules-hparams",
  "brief":"Plot the LR-vs-step curve for the schedules the book uses. Controls: total steps, warmup steps, peak LR, min-LR ratio, and schedule = {linear-warmup+cosine, WSD (warmup-stable-decay, with a decay-fraction slider), inverse-sqrt, constant}. Draw the curve on an axis-labeled plot that updates live; mark the warmup end and (for WSD) the decay start. Overlay two schedules to compare. Compute the exact formulas (cosine: min + 0.5*(peak-min)*(1+cos(pi*t)); WSD: linear/constant/sqrt-decay legs). Annotate why WSD's long stable phase + short decay pairs with mid-training annealing (cross-link the capstone)."},
 {"slug":"flash-attention-tiling","title":"FlashAttention tiling & online softmax","chapter":"04-kernels-efficiency/02-flash-attention-1",
  "brief":"Animate why FlashAttention never materializes the full S x S score matrix. Show the Q, K, V as row/column strips split into blocks (block-size slider). Step through the outer loop over K/V blocks: for the current block, highlight the tile of scores computed, and update the running per-row max m and running sum l and the running output accumulator O via the online-softmax rescale (show m_new = max(m, block_max), the correction factor exp(m_old - m_new), and O rescaled). A memory meter contrasts O(S^2) materialized scores (naive) vs O(block) SRAM tiles (flash). Keep the online-softmax recurrence exact on small toy numbers so the running stats visibly converge to the true softmax attention."},
 {"slug":"decoding-tree","title":"Decoding strategies: greedy, beam, sampling","chapter":"07-inference-serving/09-sampling-decoding",
  "brief":"An interactive next-token decoding tree over a tiny toy vocabulary with fixed seeded conditional probabilities. Choose a strategy: greedy (argmax path), beam search (beam-width slider, keep top-B cumulative-logprob sequences, show the surviving beams and pruned branches), temperature sampling (temp slider), and top-k / top-p / nucleus (k, p sliders showing which tokens are kept/cut). Draw the expanding tree for a few steps, labeling edges with probabilities and highlighting the chosen/kept paths and the pruned ones. Show the resulting sequence(s) and their total logprob. Teaches: greedy vs beam vs sampling, how beam width and top-k/top-p reshape the candidate set, the diversity/quality tradeoff. Real probability math (cumulative logprobs, top-k/top-p truncation + renormalize)."},
 {"slug":"speculative-decoding-viz","title":"Speculative decoding: draft, verify, accept","chapter":"07-inference-serving/06-speculative-decoding",
  "brief":"Animate the draft-then-verify loop. A small fast 'draft' model proposes gamma tokens (gamma slider); the big 'target' model verifies them in one parallel pass; accept the longest matching prefix and reject the rest, then sample one bonus token — animate the accept/reject per step. An 'acceptance rate' slider (or draft/target agreement) drives how many are accepted. Show the expected tokens-per-target-call = (1 - alpha^(gamma+1))/(1 - alpha) and the resulting wall-clock speedup vs plain decode given a draft/target cost ratio slider. Teaches: why speculative decoding is lossless (verification distribution is exact), and how speedup depends on acceptance rate and gamma. Real geometric-acceptance math."},
 {"slug":"precision-formats","title":"Floating-point formats: fp32, bf16, fp16, fp8, int8","chapter":"01-foundations/04-numerics-precision",
  "brief":"Show the bit layout and tradeoffs of the numeric formats used in training/inference. A format selector (fp32, tf32, bf16, fp16, fp8-e4m3, fp8-e5m2, int8) draws the sign/exponent/mantissa bit fields with their widths. Enter a real number and show: its nearest representable value in the chosen format, the rounding error, and where it sits relative to the format's dynamic range (max finite, smallest normal/subnormal) and machine epsilon. A comparison table of the selected vs fp32 (exponent bits, mantissa bits, dynamic range, relative precision). Demonstrate the key point: bf16 keeps fp32's exponent range (few overflow issues) but only ~3 decimal digits of precision; fp16 has more mantissa but narrow range (overflow); fp8 needs per-tensor scaling. Compute the actual decomposition and rounding for the entered value."},
 {"slug":"gqa-mla-explorer","title":"MHA vs MQA vs GQA vs MLA: KV heads & cache","chapter":"02-transformer/04-mha-gqa-mla",
  "brief":"Visualize how query heads share key/value heads across the attention variants. Controls: n_heads (query heads), and a variant selector MHA (n_kv=n_heads), MQA (n_kv=1), GQA (n_kv=g, group-size slider), MLA (low-rank latent, latent-dim slider). Draw the query heads as boxes and the KV heads as boxes with lines showing which queries share which KV head (grouping). Show the KV-cache size per token for each variant (2 * n_kv * head_dim * bytes, and for MLA the latent-dim compression) and the ratio vs MHA. Teaches: GQA interpolates MHA<->MQA trading quality for KV-cache; MLA compresses KV into a latent for an even smaller cache (DeepSeek). Compute exact KV-cache bytes and the compression ratios."},
 # ---- Batch 2 (token-heavy first): RL, agents, RAG, distributed, inference internals, interp ----
 {"slug":"transformer-forward-pass","title":"A full transformer forward pass, stage by stage","chapter":"02-transformer/07-build-gpt-from-scratch",
  "brief":"A GUIDED, animated walkthrough of one forward pass of a small GPT, with a 'Next stage' / 'Play' stepper. Stages, each highlighted in a data-flow diagram with the running TENSOR SHAPE annotated: (1) token ids [B,T]; (2) token + positional embeddings -> [B,T,d]; (3) inside one transformer block: RMSNorm -> QKV projection -> multi-head split -> scaled dot-product attention (show a small attention heatmap) -> output proj -> residual add -> RMSNorm -> SwiGLU MLP -> residual add; (4) repeat over N layers (a layer counter); (5) final norm -> lm_head [B,T,V] -> softmax -> next-token distribution. Use tiny concrete dims (B=1, T=4, d=8, heads=2, V=16) and compute REAL numbers with fixed seeded weights so the shown activations/shapes are correct at every stage. A side panel narrates what each stage does and why. This is the flagship 'see the whole model' visualizer — make the shape-tracking and the residual stream legible."},
 {"slug":"rlhf-ppo-pipeline","title":"RLHF with PPO: the full loop","chapter":"05-posttraining-alignment/06-ppo-for-llms",
  "brief":"Animate the complete PPO-RLHF loop as a cycle diagram with a 'step' button that advances one iteration: prompt -> POLICY generates a response (show a short token sequence) -> REWARD MODEL scores it (a scalar r) -> per-token advantages via GAE (show the value baseline) -> the PPO clipped surrogate objective (show the probability ratio pi/pi_old, the clip band [1-eps,1+eps], and which tokens are clipped) -> a KL penalty to the reference/SFT policy (a slider for the KL coefficient beta) -> policy update. Include a small live plot of reward vs KL over iterations showing the classic tradeoff (raise beta -> lower KL but lower reward; reward hacking when beta too small). Compute the real clipped-objective and KL-per-token math on toy seeded numbers. Label the FOUR models (policy, reference, reward, value/critic). Token-heavy and central to alignment."},
 {"slug":"rag-pipeline","title":"RAG pipeline: retrieve, augment, generate","chapter":"09-rag-retrieval/03-rag-architectures",
  "brief":"An end-to-end RAG animation. A user query is embedded to a point in a 2D space that also holds ~12 document-chunk points (seeded); show the top-k nearest chunks by cosine similarity (draw the query point, the neighborhood circle, and lines to the retrieved chunks with their similarity scores). Then assemble the augmented prompt (system + retrieved context + query) shown as stacked blocks with a token-budget bar, and 'generate' a grounded answer that cites the retrieved chunks. Controls: k (top-k slider), a similarity threshold, and a toggle for a reranker step (re-order the retrieved set by a second score). Teaches the whole retrieve->rerank->augment->generate flow, why chunking + top-k + context-window budget interact, and grounding/citation. Real cosine-similarity + top-k math on the 2D points."},
 {"slug":"react-agent-loop","title":"A ReAct agent loop: thought, action, observation","chapter":"08-agents-harness/02-agentic-loop",
  "brief":"Animate a ReAct agent solving a small toy task (e.g. a 2-step arithmetic-with-lookup question) as an interactive transcript that reveals one step at a time on 'Next step': Thought -> Action (a tool call, e.g. calculator(...) or search(...)) -> Observation (the tool result) -> ... -> Final Answer. Draw the loop as a cycle (LLM <-> tools <-> environment) with the growing context/scratchpad shown as an accumulating block (and a context-length bar). Include a 'the model can go wrong' toggle that injects a bad tool call and shows recovery on the next thought. Controls: pick one of 2-3 preset tasks; max-steps slider. Teaches the interleaved reason/act pattern, tools as the agent's hands, the growing context, and the stopping condition. Deterministic scripted trajectories (no LLM call); make the loop and the scratchpad growth the stars."},
 {"slug":"parallelism-visualizer","title":"How a model is split across GPUs: DP, TP, PP, FSDP","chapter":"03-pretraining/06-distributed-model-parallel","effort":"high",
  "brief":"Show, on a grid of GPUs, how each parallelism strategy partitions the model+batch, with a per-GPU memory bar. A selector: Data Parallel (full model replicated, batch split; all-reduce gradients), Tensor Parallel (each layer's matrices sharded across GPUs; all-reduce activations within a layer), Pipeline Parallel (layers grouped into stages across GPUs; show the micro-batch pipeline bubble), FSDP/ZeRO (params+grads+optimizer-state sharded; all-gather in forward, reduce-scatter in backward). For the chosen strategy, animate ONE training step highlighting which GPU holds what and the communication (arrows labeled all-reduce / all-gather / reduce-scatter / P2P) and update each GPU's memory bar (params/grads/opt-state/activations). Controls: number of GPUs, model size, batch. Compute the real per-GPU memory split for each strategy (e.g. FSDP divides the 16-bytes/param optimizer+grad+master state by world size). The single best 'why do we need all these parallelisms' visual."},
 {"slug":"paged-attention-blocks","title":"PagedAttention: KV cache as paged blocks","chapter":"04-kernels-efficiency/06-paged-attention-kv",
  "brief":"Visualize vLLM-style PagedAttention. Show the physical KV 'GPU memory' as a grid of fixed-size blocks (block_size slider, e.g. 16 tokens). Several sequences (rows) each grow token by token on a 'decode step'; each maps to a block table (logical->physical block ids) drawn as arrows into the physical grid, filling the last block partially. Contrast with a 'contiguous pre-allocation' toggle that reserves max_seq_len per sequence and shows the massive INTERNAL FRAGMENTATION / wasted memory the paged scheme avoids. Add prefix sharing: two sequences with a common prompt point their early block-table entries at the SAME physical blocks (copy-on-write). Show a utilization meter (used vs wasted). Teaches paging, the block table, near-zero fragmentation, and prefix/KV sharing. Real block accounting (ceil(seq/block_size) blocks, wasted = blocks*block_size - tokens)."},
 {"slug":"continuous-batching-scheduler","title":"Continuous (iteration-level) batching","chapter":"07-inference-serving/02-continuous-batching","effort":"high",
  "brief":"Animate iteration-level scheduling on a timeline. Requests arrive over time (each with its own prompt length + output length); a scheduler forms a running batch capped by max_num_seqs and a token budget. Step through iterations: at each decode iteration show the current running batch (a set of bars advancing one token), a finished request LEAVING mid-batch (its slot freed), and a waiting request ADMITTED into the freed slot immediately (that is the whole point vs static batching). Include a chunked-prefill toggle (a long prompt's prefill is split across iterations so it doesn't stall decodes) and a preemption event when KV memory is full (a request is swapped/recomputed). Show live GPU-utilization and throughput vs a 'static batching' comparison (which idles until the whole batch finishes). Controls: arrival rate, max batch, token budget. Real slot/token accounting; this is the core serving-throughput idea."},
 {"slug":"induction-head","title":"An induction head, mechanistically","chapter":"13-interp-safety-gov/01-mechanistic-interpretability",
  "brief":"Illustrate the canonical induction-head circuit that implements in-context copying ([A][B]...[A]->[B]). Show a token sequence with a repeated pattern (e.g. '... D E ... D ?'). Two-part animation: (1) the PREVIOUS-TOKEN head writes, at each position, information about the token before it; (2) the INDUCTION head at the final [D] attends BACK to the position right after the earlier [D] (draw the attention arrow) and copies that token [E] to the output, predicting [E] next. Show the two heads' attention patterns as small heatmaps and the Q-composition between them (the induction head's query reads what the prev-token head wrote). Let the user edit the sequence / move the repeated token and watch the induction attention follow. Teaches attention-head composition, why induction heads underlie in-context learning, and how mech-interp reads a circuit. Deterministic pattern-matching model of the two heads."},
 {"slug":"dpo-explorer","title":"DPO: preferences into a policy, no reward model","chapter":"05-posttraining-alignment/07-dpo-and-variants",
  "brief":"Show how Direct Preference Optimization turns a (prompt, chosen, rejected) triple into a gradient without a separate reward model. For a preference pair, show the four log-probs (policy and reference, on chosen and rejected), the implicit reward r = beta*log(pi/pi_ref), the DPO logistic loss -log sigmoid(beta*(r_chosen - r_rejected)), and how a gradient step raises the chosen margin and lowers the rejected one (animate the two log-prob bars moving apart, with the reference anchoring them). A beta slider shows the KL-vs-sharpness tradeoff. Plot the loss as the margin grows. Teaches DPO as classification on preference pairs, the implicit reward, and beta's role. Real sigmoid/log-prob math on seeded numbers; contrast one line with PPO-RLHF."},
 {"slug":"grpo-advantage","title":"GRPO: group-relative advantages","chapter":"05-posttraining-alignment/08-grpo-rloo",
  "brief":"Visualize GRPO's critic-free advantage. For one prompt, sample a GROUP of G responses (G slider); each gets a (verifiable) reward shown as a bar. Compute the group-relative advantage A_i = (r_i - mean(r)) / std(r) and draw each response's advantage as a signed bar (above/below the group mean line), so above-average responses are pushed up and below-average down — no value network needed. Show a degenerate all-correct or all-wrong group collapsing to zero advantage (motivating dynamic sampling / DAPO). A 'reward spread' control changes the variance. Teaches why the group mean is the baseline, the normalization, and the zero-variance failure. Real mean/std/advantage math; contrast with PPO's learned value baseline."},
 {"slug":"lora-lowrank","title":"LoRA: adapting a weight with a low-rank update","chapter":"05-posttraining-alignment/03-peft-lora-qlora",
  "brief":"Show W' = W + (alpha/r) B A. Draw the frozen d x d weight W as a grid, and the trainable A (r x d) and B (d x r) as thin strips; a rank slider r changes the strip width and updates the trainable-parameter count (2*r*d) and the compression vs full fine-tuning (d^2 / 2rd). Visualize the low-rank update BA as an outline heatmap over W and the scaling alpha/r. Include a QLoRA note (W stored in NF4, adapters in bf16). Teaches why a tiny r captures most of the useful update, the parameter savings, and the alpha/r scaling. Real param-count + rank math (this complements the ag-lora-params self-check with a geometric view)."},
 {"slug":"scaling-law-fit","title":"Fit your own scaling law and extrapolate","chapter":"03-pretraining/04-scaling-laws",
  "brief":"Interactive scaling-law fitting. Show a handful of (N, D, loss) data points from small 'ladder' runs on a loss-vs-compute (log-log) plot; fit L = E + A/N^alpha + B/D^beta (or the compute form L = E + (C0/C)^a) via least squares and draw the fitted curve, then EXTRAPOLATE a dashed line to a target compute the user picks with a slider, showing the predicted loss. Let the user add noise to the points or drag one to see the fit + extrapolation update (and how a bad point misleads the extrapolation). Also mark the compute-optimal N*,D* for a chosen budget (the Chinchilla ~20 tokens/param point) and the over-trained regime. Teaches fit-then-extrapolate, why you run a ladder before the big run, and extrapolation risk. Real log-log least-squares fit (closed form)."},
 {"slug":"reward-model-preference","title":"Reward modeling from human preferences","chapter":"05-posttraining-alignment/05-rlhf-reward-modeling",
  "brief":"Show how pairwise human preferences train a scalar reward model via the Bradley-Terry model. Present several (response A vs response B) comparisons with a human 'chosen' label; the model assigns each response a scalar reward, and P(A preferred) = sigmoid(r_A - r_B). Animate a training step raising the chosen reward and lowering the rejected one to match the labels (loss = -log sigmoid(r_chosen - r_rejected)); show the accuracy on the pairs climbing. Add a slider for label noise / disagreement showing the reward model's ceiling, and a note on reward over-optimization (Goodhart) when a policy exploits it. Teaches Bradley-Terry, why rewards are only meaningful up to differences (relative not absolute), and preference-data quality. Real sigmoid/BT math on seeded pairs."},
 {"slug":"watermark-greenlist","title":"LLM watermarking: the green-list rule","chapter":"13-interp-safety-gov/04-watermarking-provenance",
  "brief":"Illustrate the Kirchenbauer-style green-list watermark. At each generation step, a hash of the previous token seeds a pseudo-random split of the vocabulary into a GREEN list (fraction gamma) and a RED list; a bias delta is added to green logits before sampling, so generated text contains more green tokens than chance. Visualize: the vocabulary colored green/red (re-seeded each step by the prior token), the sampled token, and a running green-token counter with a z-score detector (z = (observed_green - gamma*T)/sqrt(T*gamma*(1-gamma))) that crosses a detection threshold as text grows — while HUMAN text stays near chance. Sliders: gamma, delta (strength), sequence length. Show the quality-vs-detectability tradeoff (higher delta = easier detection but more distortion). Real hashing-split + z-score math; deterministic."},
 {"slug":"long-context-rope-scaling","title":"Extending context: RoPE frequency scaling & YaRN","chapter":"03-pretraining/13-long-context-pretraining",
  "brief":"Show how a model trained at length L_train is extended to a longer L_target by rescaling RoPE frequencies. Plot the rotation angle vs position for each RoPE dimension pair; a method selector: none (angles run off the trained range past L_train -> extrapolation failure), position-interpolation (compress positions by L_train/L_target so max angle stays in-range), NTK-aware / base scaling (increase theta so low frequencies stretch while high frequencies stay), YaRN (per-frequency: interpolate low freqs, keep high freqs, with a temperature). Highlight the 'in-distribution vs out-of-distribution angle' band the model saw in training, and show which method keeps positions inside it. Sliders: L_train, L_target, theta. Teaches why naive extrapolation breaks and how each scaling keeps the effective angles trained. Real RoPE angle math (m/theta^(2i/d) with the scaling applied)."},
]


BUILD = r"""You are building ONE interactive, self-contained visualizer widget for a definitive LLM-systems web textbook. It must teach a concept through direct manipulation and be CORRECT, beautiful, and dependency-free.

Tool: {TITLE}  (slug: {SLUG})
It teaches / does:
{BRIEF}

WRITE the widget to EXACTLY: {TOOL_PATH}
Structure (match the book's other tools):
  - A single root `<div class="viz-tool" id="tool-{SLUG}">` containing: a `<div class="vt-title">{TITLE}</div>`, the controls (labels + inputs/sliders/selects, grouped in a `<div class="vt-grid">`), the visualization area (inline SVG and/or DOM/canvas), a live readout, and a short `<div class="vt-note">` explaining the takeaway.
  - A scoped `<style>` (EVERY selector prefixed with `#tool-{SLUG}`) and an inline `<script>` (an IIFE; all element ids prefixed `{SLUG}-` to avoid collisions; no globals leaking).
HARD CONSTRAINTS:
  - COMPLETELY SELF-CONTAINED: no external scripts, stylesheets, fonts, images, CDNs, network/fetch/XHR. Pure vanilla JS + inline SVG/canvas. It must work offline pasted into a page.
  - CORRECTNESS IS THE POINT: implement the REAL math (softmax with max-subtraction, exact BPE merges, exact optimizer updates, exact KV-cache bytes, exact quantization scale/round/dequant, exact online-softmax recurrence, etc.). Deterministic where randomness is used (seed a small PRNG). No fabricated formulas.
  - THEME-SAFE (light + dark): NEVER hardcode a primary color. Use CSS vars with hex fallbacks: var(--accent,#4f46e5), var(--ink,#1a1a2e), var(--ink-soft,#556), var(--muted,#889), var(--surface,#fff), var(--surface-2,#f6f7f9), var(--surface-3,#eceef3), var(--border,#e5e7eb), var(--border-2,#e5e7eb), var(--good,#2f9e6e), var(--warn,#e0a106), var(--mono,monospace), var(--sans,sans-serif). Text must be readable in both themes.
  - RESPONSIVE: fluid width, SVG uses viewBox, wide content scrolls inside its own container; never overflow the page horizontally. Inputs are keyboard-accessible with `<label>`s; add aria-labels.
  - ASCII-only in code/markup (use ->, <=, x, theta written out, HTML entities like &times; &rarr; &sigma; are fine). No console errors; guard against empty/invalid input.
INTERACTIVITY: it must update live on input (attach event listeners; render once on load). Keep it snappy.
Then INSERT the marker `{{tool:{SLUG}}}` on its own line into content/{CHAPTER}.md at the most pedagogically relevant spot (right after the section that explains this concept; a blank line before and after). Do NOT remove or alter any existing content, code fence, figure marker, or exercise.{REBUILD_NOTE}
Return a short JSON summary (file, inserted_marker, controls, what_it_teaches)."""

VERIFY = r"""You are the Opus verifier for ONE interactive textbook visualizer. Make it correct, dependency-free, theme-safe, and genuinely instructive, then fix it in place.

Tool file: {TOOL_PATH}   (slug {SLUG})
Chapter with the marker: content/{CHAPTER}.md

Read the tool file (and the chapter section around the {{tool:{SLUG}}} marker). Verify HARD and FIX in place (rewrite {TOOL_PATH}):
  1. CORRECTNESS: re-derive the math the widget computes and check the code implements it exactly (softmax/BPE/optimizer/KV-cache/quantization/online-softmax/etc.). Fix any wrong formula, off-by-one, or misleading visualization. Verify determinism (seeded PRNG).
  2. SELF-CONTAINED: NO external scripts/styles/fonts/images/CDN/network. If any exist, inline or remove them. Pure vanilla JS + inline SVG/canvas only.
  3. JS VALIDITY: the inline <script> must be syntactically valid and error-free on load and on every control change; guard invalid/empty inputs. (Mentally execute the event handlers.)
  4. THEME-SAFETY: no hardcoded primary colors; CSS vars with hex fallbacks; readable in light AND dark. All selectors and element ids scoped/prefixed to #tool-{SLUG} / {SLUG}- (no collisions with other tools on the /tools hub page, which concatenates all of them).
  5. UX: labeled, keyboard-accessible controls; responsive (viewBox SVG, no horizontal page overflow); a clear vt-title and a vt-note stating the takeaway; live updates.
  6. MARKER: confirm exactly one `{{tool:{SLUG}}}` marker exists in content/{CHAPTER}.md at a sensible spot and that no other chapter content/code/figure/exercise was damaged. Fix if needed.
Return the verdict object (file, correct, self_contained, theme_safe, issues_fixed, notes)."""

BSCHEMA = {"type":"object","additionalProperties":False,"required":["file","what_it_teaches"],
           "properties":{"file":{"type":"string"},"inserted_marker":{"type":"boolean"},
                         "controls":{"type":"array","items":{"type":"string"}},"what_it_teaches":{"type":"string"}}}
VSCHEMA = {"type":"object","additionalProperties":False,"required":["file","correct","self_contained","theme_safe","notes"],
           "properties":{"file":{"type":"string"},"correct":{"type":"boolean"},"self_contained":{"type":"boolean"},
                         "theme_safe":{"type":"boolean"},"issues_fixed":{"type":"integer"},"notes":{"type":"string"}}}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "scripts", "wf_tools.js"))
    ap.add_argument("--ids", nargs="*", default=[])
    a = ap.parse_args()
    specs = [s for s in SPECS if not a.ids or s["slug"] in a.ids]

    jobs = []
    for s in specs:
        tool_path = os.path.join(ROOT, "tools", s["slug"] + ".html")
        rebuild_note = ("\n\nNOTE: this tool ALREADY EXISTS and is already referenced by {{tool:%s}} markers in the "
                        "book — OVERWRITE %s with the improved version and do NOT insert any new marker (skip the marker step)."
                        % (s["slug"], tool_path)) if s.get("rebuild") else ""
        def fill(t):
            return (t.replace("{TITLE}", s["title"]).replace("{SLUG}", s["slug"])
                    .replace("{BRIEF}", s["brief"]).replace("{TOOL_PATH}", tool_path)
                    .replace("{CHAPTER}", s["chapter"]).replace("{REBUILD_NOTE}", rebuild_note))
        jobs.append({"slug": s["slug"], "build": fill(BUILD), "verify": fill(VERIFY),
                     "model": "claude-opus-5" if s.get("effort") == "high" else "sonnet"})

    js = f"""export const meta = {{
  name: 'interactive-tools',
  description: 'Build {len(jobs)} interactive visualizer tools (Sonnet build -> Opus verify)',
  phases: [{{ title: 'Build' }}, {{ title: 'Verify' }}],
}}
const JOBS = {json.dumps(jobs, ensure_ascii=True)};
const BSCHEMA = {json.dumps(BSCHEMA)};
const VSCHEMA = {json.dumps(VSCHEMA)};
log('Building ' + JOBS.length + ' interactive tools (build -> Opus verify)…');
const results = await pipeline(
  JOBS,
  function (j) {{
    return agent(j.build, {{ label: 'build:' + j.slug, phase: 'Build', model: j.model, schema: BSCHEMA }})
      .then(function (r) {{ return j; }});
  }},
  async function (j) {{
    if (!j) return null;
    const v = await agent(j.verify, {{ label: 'verify:' + j.slug, phase: 'Verify', model: 'claude-opus-5', schema: VSCHEMA }});
    return {{ slug: j.slug, verify: v }};
  }}
);
const done = results.filter(Boolean);
log('Interactive tools: ' + done.length + '/' + JOBS.length + ' built+verified.');
return {{ total: JOBS.length, done: done.length, results: results }};
"""
    open(a.out, "w").write(js)
    print(f"Wrote {a.out}: {len(jobs)} tools")
    for s in specs:
        print(f"  {'[rebuild] ' if s.get('rebuild') else '[new]     '}{s['slug']:28} -> {s['chapter']}")


if __name__ == "__main__":
    main()
