export const meta = {
  name: 'exercises-b13',
  description: 'Author + verify exercises for 6 chapters',
  phases: [{ title: 'Author' }, { title: 'Verify' }],
}
const CH = [
  {
    "chapter": "06-rl-infra/08-reward-verifiers-sandboxes",
    "author": "You are writing END-OF-CHAPTER EXERCISES for the textbook \"The LLM Stack\".\nBook root: /local-ssd/pk669/programming/llm-stack-textbook. Chapter: content/06-rl-infra/08-reward-verifiers-sandboxes.md  (READ IT FULLY FIRST.)\n\nAppend a new section to the END of content/06-rl-infra/08-reward-verifiers-sandboxes.md (use the Edit tool; append after the last\nline, do not disturb existing content). The section:\n\n## Exercises\n\nThen 3-6 exercises that genuinely test THIS chapter's core ideas \u2014 a mix of:\n  - conceptual (\"why does ... / what happens if ...\"),\n  - quantitative (a small calculation with concrete numbers the reader can do by hand),\n  - and at least one implementation task (\"implement / modify ...\" tied to the chapter's code).\nOrder them roughly easy -> hard. Number them **1.**, **2.**, ...\n\nAfter EACH exercise, put its worked solution in a COLLAPSIBLE block using this exact syntax\n(pymdownx.details \u2014 starts collapsed):\n\n    ??? note \"Solution\"\n        <the full worked solution, indented 4 spaces>\n\nSolutions must be COMPLETE and CORRECT: show the reasoning/derivation or the code; for quantitative\nproblems, work the arithmetic to a final number; for implementation problems, give runnable code\nconsistent with the chapter's style. Ground everything in the chapter \u2014 no facts the chapter doesn't\nsupport. Keep math in the book's `$...$`/`$$...$$` style and code in fenced blocks. ASCII-safe.\n\nMUST PRESERVE: do not alter the chapter's existing prose, code, {{fig:}}/{{tool:}} markers, or\nadmonitions. Only APPEND the Exercises section.\n\nReturn one short line: how many exercises you wrote.",
    "verify": "You are VERIFYING the '## Exercises' section just appended to content/06-rl-infra/08-reward-verifiers-sandboxes.md.\nRead the chapter AND the exercises. For EACH exercise's solution:\n  - Re-derive / re-compute it independently. Is it CORRECT? (Fix any wrong number, formula, or claim.)\n  - Is it grounded in the chapter (no unsupported facts)? Is the collapsible `??? note \"Solution\"`\n    syntax well-formed (4-space indented body)? Is any code consistent with the chapter and runnable?\n  - Is the exercise itself well-posed and unambiguous?\nFix problems directly by editing the chapter. Also confirm you did NOT break existing content\n(markers/admonitions/code fences intact). Set passed only when every solution is correct and\nwell-formed. Report n_exercises and the corrections you made."
  },
  {
    "chapter": "06-rl-infra/09-advantage-kl-tricks",
    "author": "You are writing END-OF-CHAPTER EXERCISES for the textbook \"The LLM Stack\".\nBook root: /local-ssd/pk669/programming/llm-stack-textbook. Chapter: content/06-rl-infra/09-advantage-kl-tricks.md  (READ IT FULLY FIRST.)\n\nAppend a new section to the END of content/06-rl-infra/09-advantage-kl-tricks.md (use the Edit tool; append after the last\nline, do not disturb existing content). The section:\n\n## Exercises\n\nThen 3-6 exercises that genuinely test THIS chapter's core ideas \u2014 a mix of:\n  - conceptual (\"why does ... / what happens if ...\"),\n  - quantitative (a small calculation with concrete numbers the reader can do by hand),\n  - and at least one implementation task (\"implement / modify ...\" tied to the chapter's code).\nOrder them roughly easy -> hard. Number them **1.**, **2.**, ...\n\nAfter EACH exercise, put its worked solution in a COLLAPSIBLE block using this exact syntax\n(pymdownx.details \u2014 starts collapsed):\n\n    ??? note \"Solution\"\n        <the full worked solution, indented 4 spaces>\n\nSolutions must be COMPLETE and CORRECT: show the reasoning/derivation or the code; for quantitative\nproblems, work the arithmetic to a final number; for implementation problems, give runnable code\nconsistent with the chapter's style. Ground everything in the chapter \u2014 no facts the chapter doesn't\nsupport. Keep math in the book's `$...$`/`$$...$$` style and code in fenced blocks. ASCII-safe.\n\nMUST PRESERVE: do not alter the chapter's existing prose, code, {{fig:}}/{{tool:}} markers, or\nadmonitions. Only APPEND the Exercises section.\n\nReturn one short line: how many exercises you wrote.",
    "verify": "You are VERIFYING the '## Exercises' section just appended to content/06-rl-infra/09-advantage-kl-tricks.md.\nRead the chapter AND the exercises. For EACH exercise's solution:\n  - Re-derive / re-compute it independently. Is it CORRECT? (Fix any wrong number, formula, or claim.)\n  - Is it grounded in the chapter (no unsupported facts)? Is the collapsible `??? note \"Solution\"`\n    syntax well-formed (4-space indented body)? Is any code consistent with the chapter and runnable?\n  - Is the exercise itself well-posed and unambiguous?\nFix problems directly by editing the chapter. Also confirm you did NOT break existing content\n(markers/admonitions/code fences intact). Set passed only when every solution is correct and\nwell-formed. Report n_exercises and the corrections you made."
  },
  {
    "chapter": "06-rl-infra/10-agentic-multiturn-rl",
    "author": "You are writing END-OF-CHAPTER EXERCISES for the textbook \"The LLM Stack\".\nBook root: /local-ssd/pk669/programming/llm-stack-textbook. Chapter: content/06-rl-infra/10-agentic-multiturn-rl.md  (READ IT FULLY FIRST.)\n\nAppend a new section to the END of content/06-rl-infra/10-agentic-multiturn-rl.md (use the Edit tool; append after the last\nline, do not disturb existing content). The section:\n\n## Exercises\n\nThen 3-6 exercises that genuinely test THIS chapter's core ideas \u2014 a mix of:\n  - conceptual (\"why does ... / what happens if ...\"),\n  - quantitative (a small calculation with concrete numbers the reader can do by hand),\n  - and at least one implementation task (\"implement / modify ...\" tied to the chapter's code).\nOrder them roughly easy -> hard. Number them **1.**, **2.**, ...\n\nAfter EACH exercise, put its worked solution in a COLLAPSIBLE block using this exact syntax\n(pymdownx.details \u2014 starts collapsed):\n\n    ??? note \"Solution\"\n        <the full worked solution, indented 4 spaces>\n\nSolutions must be COMPLETE and CORRECT: show the reasoning/derivation or the code; for quantitative\nproblems, work the arithmetic to a final number; for implementation problems, give runnable code\nconsistent with the chapter's style. Ground everything in the chapter \u2014 no facts the chapter doesn't\nsupport. Keep math in the book's `$...$`/`$$...$$` style and code in fenced blocks. ASCII-safe.\n\nMUST PRESERVE: do not alter the chapter's existing prose, code, {{fig:}}/{{tool:}} markers, or\nadmonitions. Only APPEND the Exercises section.\n\nReturn one short line: how many exercises you wrote.",
    "verify": "You are VERIFYING the '## Exercises' section just appended to content/06-rl-infra/10-agentic-multiturn-rl.md.\nRead the chapter AND the exercises. For EACH exercise's solution:\n  - Re-derive / re-compute it independently. Is it CORRECT? (Fix any wrong number, formula, or claim.)\n  - Is it grounded in the chapter (no unsupported facts)? Is the collapsible `??? note \"Solution\"`\n    syntax well-formed (4-space indented body)? Is any code consistent with the chapter and runnable?\n  - Is the exercise itself well-posed and unambiguous?\nFix problems directly by editing the chapter. Also confirm you did NOT break existing content\n(markers/admonitions/code fences intact). Set passed only when every solution is correct and\nwell-formed. Report n_exercises and the corrections you made."
  },
  {
    "chapter": "06-rl-infra/11-scaling-rl-tricks",
    "author": "You are writing END-OF-CHAPTER EXERCISES for the textbook \"The LLM Stack\".\nBook root: /local-ssd/pk669/programming/llm-stack-textbook. Chapter: content/06-rl-infra/11-scaling-rl-tricks.md  (READ IT FULLY FIRST.)\n\nAppend a new section to the END of content/06-rl-infra/11-scaling-rl-tricks.md (use the Edit tool; append after the last\nline, do not disturb existing content). The section:\n\n## Exercises\n\nThen 3-6 exercises that genuinely test THIS chapter's core ideas \u2014 a mix of:\n  - conceptual (\"why does ... / what happens if ...\"),\n  - quantitative (a small calculation with concrete numbers the reader can do by hand),\n  - and at least one implementation task (\"implement / modify ...\" tied to the chapter's code).\nOrder them roughly easy -> hard. Number them **1.**, **2.**, ...\n\nAfter EACH exercise, put its worked solution in a COLLAPSIBLE block using this exact syntax\n(pymdownx.details \u2014 starts collapsed):\n\n    ??? note \"Solution\"\n        <the full worked solution, indented 4 spaces>\n\nSolutions must be COMPLETE and CORRECT: show the reasoning/derivation or the code; for quantitative\nproblems, work the arithmetic to a final number; for implementation problems, give runnable code\nconsistent with the chapter's style. Ground everything in the chapter \u2014 no facts the chapter doesn't\nsupport. Keep math in the book's `$...$`/`$$...$$` style and code in fenced blocks. ASCII-safe.\n\nMUST PRESERVE: do not alter the chapter's existing prose, code, {{fig:}}/{{tool:}} markers, or\nadmonitions. Only APPEND the Exercises section.\n\nReturn one short line: how many exercises you wrote.",
    "verify": "You are VERIFYING the '## Exercises' section just appended to content/06-rl-infra/11-scaling-rl-tricks.md.\nRead the chapter AND the exercises. For EACH exercise's solution:\n  - Re-derive / re-compute it independently. Is it CORRECT? (Fix any wrong number, formula, or claim.)\n  - Is it grounded in the chapter (no unsupported facts)? Is the collapsible `??? note \"Solution\"`\n    syntax well-formed (4-space indented body)? Is any code consistent with the chapter and runnable?\n  - Is the exercise itself well-posed and unambiguous?\nFix problems directly by editing the chapter. Also confirm you did NOT break existing content\n(markers/admonitions/code fences intact). Set passed only when every solution is correct and\nwell-formed. Report n_exercises and the corrections you made."
  },
  {
    "chapter": "06-rl-infra/12-rl-data-curriculum-replay",
    "author": "You are writing END-OF-CHAPTER EXERCISES for the textbook \"The LLM Stack\".\nBook root: /local-ssd/pk669/programming/llm-stack-textbook. Chapter: content/06-rl-infra/12-rl-data-curriculum-replay.md  (READ IT FULLY FIRST.)\n\nAppend a new section to the END of content/06-rl-infra/12-rl-data-curriculum-replay.md (use the Edit tool; append after the last\nline, do not disturb existing content). The section:\n\n## Exercises\n\nThen 3-6 exercises that genuinely test THIS chapter's core ideas \u2014 a mix of:\n  - conceptual (\"why does ... / what happens if ...\"),\n  - quantitative (a small calculation with concrete numbers the reader can do by hand),\n  - and at least one implementation task (\"implement / modify ...\" tied to the chapter's code).\nOrder them roughly easy -> hard. Number them **1.**, **2.**, ...\n\nAfter EACH exercise, put its worked solution in a COLLAPSIBLE block using this exact syntax\n(pymdownx.details \u2014 starts collapsed):\n\n    ??? note \"Solution\"\n        <the full worked solution, indented 4 spaces>\n\nSolutions must be COMPLETE and CORRECT: show the reasoning/derivation or the code; for quantitative\nproblems, work the arithmetic to a final number; for implementation problems, give runnable code\nconsistent with the chapter's style. Ground everything in the chapter \u2014 no facts the chapter doesn't\nsupport. Keep math in the book's `$...$`/`$$...$$` style and code in fenced blocks. ASCII-safe.\n\nMUST PRESERVE: do not alter the chapter's existing prose, code, {{fig:}}/{{tool:}} markers, or\nadmonitions. Only APPEND the Exercises section.\n\nReturn one short line: how many exercises you wrote.",
    "verify": "You are VERIFYING the '## Exercises' section just appended to content/06-rl-infra/12-rl-data-curriculum-replay.md.\nRead the chapter AND the exercises. For EACH exercise's solution:\n  - Re-derive / re-compute it independently. Is it CORRECT? (Fix any wrong number, formula, or claim.)\n  - Is it grounded in the chapter (no unsupported facts)? Is the collapsible `??? note \"Solution\"`\n    syntax well-formed (4-space indented body)? Is any code consistent with the chapter and runnable?\n  - Is the exercise itself well-posed and unambiguous?\nFix problems directly by editing the chapter. Also confirm you did NOT break existing content\n(markers/admonitions/code fences intact). Set passed only when every solution is correct and\nwell-formed. Report n_exercises and the corrections you made."
  },
  {
    "chapter": "07-inference-serving/01-anatomy-inference",
    "author": "You are writing END-OF-CHAPTER EXERCISES for the textbook \"The LLM Stack\".\nBook root: /local-ssd/pk669/programming/llm-stack-textbook. Chapter: content/07-inference-serving/01-anatomy-inference.md  (READ IT FULLY FIRST.)\n\nAppend a new section to the END of content/07-inference-serving/01-anatomy-inference.md (use the Edit tool; append after the last\nline, do not disturb existing content). The section:\n\n## Exercises\n\nThen 3-6 exercises that genuinely test THIS chapter's core ideas \u2014 a mix of:\n  - conceptual (\"why does ... / what happens if ...\"),\n  - quantitative (a small calculation with concrete numbers the reader can do by hand),\n  - and at least one implementation task (\"implement / modify ...\" tied to the chapter's code).\nOrder them roughly easy -> hard. Number them **1.**, **2.**, ...\n\nAfter EACH exercise, put its worked solution in a COLLAPSIBLE block using this exact syntax\n(pymdownx.details \u2014 starts collapsed):\n\n    ??? note \"Solution\"\n        <the full worked solution, indented 4 spaces>\n\nSolutions must be COMPLETE and CORRECT: show the reasoning/derivation or the code; for quantitative\nproblems, work the arithmetic to a final number; for implementation problems, give runnable code\nconsistent with the chapter's style. Ground everything in the chapter \u2014 no facts the chapter doesn't\nsupport. Keep math in the book's `$...$`/`$$...$$` style and code in fenced blocks. ASCII-safe.\n\nMUST PRESERVE: do not alter the chapter's existing prose, code, {{fig:}}/{{tool:}} markers, or\nadmonitions. Only APPEND the Exercises section.\n\nReturn one short line: how many exercises you wrote.",
    "verify": "You are VERIFYING the '## Exercises' section just appended to content/07-inference-serving/01-anatomy-inference.md.\nRead the chapter AND the exercises. For EACH exercise's solution:\n  - Re-derive / re-compute it independently. Is it CORRECT? (Fix any wrong number, formula, or claim.)\n  - Is it grounded in the chapter (no unsupported facts)? Is the collapsible `??? note \"Solution\"`\n    syntax well-formed (4-space indented body)? Is any code consistent with the chapter and runnable?\n  - Is the exercise itself well-posed and unambiguous?\nFix problems directly by editing the chapter. Also confirm you did NOT break existing content\n(markers/admonitions/code fences intact). Set passed only when every solution is correct and\nwell-formed. Report n_exercises and the corrections you made."
  }
]
const VERIFY_SCHEMA = {"type": "object", "additionalProperties": false, "required": ["chapter", "passed", "n_exercises", "corrections", "notes"], "properties": {"chapter": {"type": "string"}, "passed": {"type": "boolean", "description": "every solution correct + grounded + well-formed"}, "n_exercises": {"type": "integer"}, "corrections": {"type": "array", "items": {"type": "string"}, "description": "solution errors you found and fixed"}, "notes": {"type": "string"}}}
const results = await pipeline(
  CH,
  c => agent(c.author, { label: `ex:${c.chapter}`, phase: 'Author', model: 'opus', effort: 'high' }).then(() => c),
  c => agent(c.verify, { label: `verify:${c.chapter}`, phase: 'Verify', schema: VERIFY_SCHEMA, model: 'opus', effort: 'high' })
        .then(v => ({ chapter: c.chapter, verdict: v })),
)
const done = results.filter(Boolean)
const passed = done.filter(r => r.verdict && r.verdict.passed).map(r => r.chapter)
const failed = done.filter(r => !r.verdict || !r.verdict.passed).map(r => r.chapter)
const corr = done.flatMap(r => (r.verdict?.corrections || []).map(c => `${r.chapter}: ${c}`))
const died = CH.filter((c,i) => !results[i]).map(c => c.chapter)
log(`exercises: ${done.length}/${CH.length} | passed ${passed.length} | corrections ${corr.length}`)
log(`PASSED: ${passed.join(' ')}`)
if (failed.length) log(`FAILED: ${failed.join(' ')}`)
if (died.length) log(`DIED: ${died.join(' ')}`)
return { passed, failed, died, corrections: corr.length }
