export const meta = {
  name: 'figure-recovery-rec2',
  description: 'Verify+fix and wire-in drafted figures for 7 chapters',
  phases: [{ title: 'Verify & wire' }],
}
const ITEMS = [{"id": "03-pretraining/14-data-mixing-curriculum", "abspath": "/local-ssd/pk669/programming/llm-stack-textbook/content/03-pretraining/14-data-mixing-curriculum.md", "names": ["doremi-reference-proxy-loop", "mixing-epoch-budget-tree"]}, {"id": "05-posttraining-alignment/05-rlhf-reward-modeling", "abspath": "/local-ssd/pk669/programming/llm-stack-textbook/content/05-posttraining-alignment/05-rlhf-reward-modeling.md", "names": ["rlhf-four-model-setup", "rlhf-three-stage-pipeline", "rm-overoptimization-curve", "rm-scalar-head-architecture"]}, {"id": "05-posttraining-alignment/06-ppo-for-llms", "abspath": "/local-ssd/pk669/programming/llm-stack-textbook/content/05-posttraining-alignment/06-ppo-for-llms.md", "names": ["ppo-four-model-passes", "ppo-mdp-trajectory"]}, {"id": "05-posttraining-alignment/09-rlvr-reasoning", "abspath": "/local-ssd/pk669/programming/llm-stack-textbook/content/05-posttraining-alignment/09-rlvr-reasoning.md", "names": ["rlvr-length-emergence-loop", "rlvr-rm-vs-verifier"]}, {"id": "06-rl-infra/07-colocated-vs-disaggregated", "abspath": "/local-ssd/pk669/programming/llm-stack-textbook/content/06-rl-infra/07-colocated-vs-disaggregated.md", "names": ["colodis-disagg-topology", "colodis-memory-timeline", "colodis-rl-iteration-loop", "colodis-sync-vs-async-timeline"]}, {"id": "12-production-mlops/03-caching-routing-cost", "abspath": "/local-ssd/pk669/programming/llm-stack-textbook/content/12-production-mlops/03-caching-routing-cost.md", "names": ["cost-routing-cascade", "cost-semantic-cache-flow", "cost-speculative-routing"]}, {"id": "12-production-mlops/06-security-prompt-injection", "abspath": "/local-ssd/pk669/programming/llm-stack-textbook/content/12-production-mlops/06-security-prompt-injection.md", "names": ["injsec-defense-five-layers", "injsec-dual-llm-pattern", "injsec-lethal-trifecta-exfil", "injsec-trust-boundary-context"]}];
const PROMPT = "You are FINISHING and VERIFYING SVG figures that were drafted for ONE chapter but not yet reviewed or wired in.\n\nChapter file: {ABSPATH}\nFigures drafted for this chapter (files at figures/<name>.html): {NAMES}\n\nFIGURE RULES (for any fixes): keep ALL content inside the viewBox with margin (text must not clip); colors ONLY via theme classes (v-fill/v-accent/v-accent-s/v-stroke/v-grid/v-muted/v-label) or var(--accent|--accent2|--good|--warn|--ink-soft|--muted) with a hex fallback \u2014 NEVER a raw hex as a primary color; NEVER use math-alphanumeric Unicode (no \ud835\udca9 \ud835\udc9f \ud835\udcdc \u211d \u2014 they tofu; use ASCII or \u03c0); NO inline <script> and NO XML comments; animate (data-anim/viz-draw/viz-sweep/viz-pulse) ONLY if it depicts a process, else keep it static; the figure must read clearly as a static image.\n\nFor EACH figure name:\n1. RENDER: run `python3 scripts/preview_fig.py <name> --theme both` from the repo root (/local-ssd/pk669/programming/llm-stack-textbook), then READ both /tmp/figpreview/<name>.light.png and /tmp/figpreview/<name>.dark.png.\n2. VERIFY vs the chapter: this figure was drawn to replace one of the chapter's ```text ASCII diagrams. Read figures/<name>.html and the chapter. Confirm the figure is FAITHFUL to that diagram's meaning and the chapter's content \u2014 every important box/node/edge/label present and correct, nothing misleading \u2014 and that it reads cleanly in BOTH light and dark (no clipping past the viewBox, no illegible overlaps) and is theme-safe. If ANYTHING is wrong, FIX figures/<name>.html (Edit) and re-render until clean.\n3. WIRE IT IN: find the ```text ... ``` fenced block in the chapter that this figure depicts, and replace that ENTIRE block with a single line `{{fig:<name>}}` (blank line before and after) using the Edit tool. If you truly cannot find a matching block (already replaced), skip only the replacement.\n\nChange nothing else in the chapter. Reply with one short line per figure: name + (PASS | fixed:<what> | wired | could-not-wire).";
phase('Verify & wire')
log('Recovering figures for ' + ITEMS.length + ' chapters…');
const results = await parallel(ITEMS.map(function (it) {
  return function () {
    const p = PROMPT.replace('{ABSPATH}', it.abspath).replace('{NAMES}', JSON.stringify(it.names));
    return agent(p, { label: 'recover:' + it.id, phase: 'Verify & wire', model: 'opus' })
      .then(function (r) { return { id: it.id, ok: true, note: r }; })
      .catch(function (e) { return { id: it.id, ok: false, note: String(e) }; });
  };
}));
log('Recovery rec2: ' + results.filter(function(r){return r.ok;}).length + '/' + ITEMS.length + ' chapters processed.');
return { batch: 'rec2', results: results };
